- include: playbooks/common.yaml
- include: playbooks/install.yaml
- include: playbooks/config_apache2.yaml
- include: playbooks/config_bind9.yaml
- include: playbooks/config_postgresql.yaml
- include: playbooks/postgresql_conexion.yaml
- include: playbooks/install_drupal.yaml
- include: playbooks/config_drupal.yaml
