---
- name: Configuración de Apache
  hosts: 10.0.0.102
  become: yes
  tasks:
  - name: Copiar el virtualhost
    copy: >
      src=files/apache2/drupal.conf
      dest=/etc/apache2/sites-available/drupal.conf
  - name: Deshabilitamos el virtualhost por defecto
    command: a2dissite 000-default.conf
  - name: Habilitamos el virtualhost nuevo
    command: a2ensite drupal.conf
    notify:
      - restart apache 

  handlers:
    - name: restart apache
      service: name=apache2 state=restarted

