---
- name: Configuración de Bind9
  hosts: 10.0.0.101
  become: yes
  tasks:
  - name: Copiar el fichero named.conf.local
    copy: >
      src=files/bind9/config/named.conf.local
      dest=/etc/bind/named.conf.local
  - name: Copiar el fichero zones.rfc1918
    copy: >
      src=files/bind9/config/zones.rfc1918
      dest=/etc/bind/zones.rfc1918
  - name: Copiar la zona directa
    copy: >
      src=files/bind9/zones/db.example.com
      dest=/var/cache/bind/db.example.com
  - name: Copiar la zona inversa
    copy: >
      src=files/bind9/zones/db.10.0.0
      dest=/var/cache/bind/db.10.0.0
  - name: change owner (and group)
    file:
      path: /var/cache/bind
      owner: bind
      group: bind
    with_items:
      - db.example.com
      - db.10.0.0
    notify:
      - restart bind 

  handlers:
    - name: restart bind
      service: name=bind9 state=restarted

