---
- name: Configuración de PostgreSQL
  hosts: 10.0.0.101
  become: yes
  become_user: postgres
  gather_facts: no

  vars:
    dbname: drupal_db
    dbuser: drupal_user
    dbpassword: drupalpassword
    ansible_ssh_pipelining: true

  tasks:
  - name: Creación de la base de datos
    postgresql_db: name={{dbname}}
  - name: Creación del usuario
    postgresql_user: db={{dbname}} name={{dbuser}} password={{dbpassword}} priv=ALL

