---
- name: Instalar paquetes necesarios nodo1
  hosts: 10.0.0.101
  become: yes
  tasks:
  - name: Instalación de PostgresSQL y Bind9
    apt: pkg={{ item }}
    with_items:
      - postgresql
      - libpq-dev
      - python-psycopg2
      - bind9

- name: Instalar paquetes necesarios nodo2
  hosts: 10.0.0.102
  become: yes
  tasks:
  - name: Instalación de Apache y Fpm-php
    apt: pkg={{ item }}
    with_items:
      - apache2
      - apache2-utils
      - libapache2-mod-php7.0
      - php7.0-fpm
      - php-pgsql

